export const data = [
  { ID: 1, Name: "John Doe", Age: 25, City: "New York" },
  { ID: 2, Name: "Jane Smith", Age: 30, City: "Los Angeles" },
  { ID: 3, Name: "Bob Johnson", Age: 22, City: "Chicago" },
  { ID: 4, Name: "Alice Williams", Age: 28, City: "San Francisco" },
  { ID: 5, Name: "Charlie Brown", Age: 35, City: "Seattle" },
  { ID: 6, Name: "Eva Davis", Age: 26, City: "Boston" },
  { ID: 7, Name: "David Lee", Age: 31, City: "Houston" },
  { ID: 8, Name: "Grace Taylor", Age: 29, City: "Atlanta" },
  { ID: 9, Name: "Frank Miller", Age: 24, City: "Denver" },
  { ID: 10, Name: "Helen Wilson", Age: 27, City: "Miami" },
  { ID: 11, Name: "George Turner", Age: 33, City: "Phoenix" },
  { ID: 12, Name: "Ivy Adams", Age: 32, City: "Dallas" },
  { ID: 13, Name: "Jack Morris", Age: 23, City: "Philadelphia" },
  { ID: 14, Name: "Karen White", Age: 34, City: "Detroit" },
  { ID: 15, Name: "Leo Davis", Age: 28, City: "San Diego" },
  { ID: 16, Name: "Megan Clark", Age: 29, City: "Minneapolis" },
  { ID: 17, Name: "Nathan Brooks", Age: 26, City: "Portland" },
  { ID: 18, Name: "Olivia Taylor", Age: 31, City: "Charlotte" },
  { ID: 19, Name: "Peter Turner", Age: 27, City: "San Antonio" },
  { ID: 20, Name: "Quincy Adams", Age: 30, City: "Austin" },
  { ID: 21, Name: "Rachel Miller", Age: 25, City: "Las Vegas" },
  { ID: 22, Name: "Samuel Wilson", Age: 32, City: "Raleigh" },
  { ID: 23, Name: "Tina Brown", Age: 29, City: "Nashville" },
  { ID: 24, Name: "Ulysses Johnson", Age: 35, City: "Kansas City" },
  { ID: 25, Name: "Victoria Adams", Age: 26, City: "Salt Lake City" },
  { ID: 26, Name: "Walter Smith", Age: 33, City: "Columbus" },
  { ID: 27, Name: "Xavier Davis", Age: 28, City: "Indianapolis" },
  { ID: 28, Name: "Yasmine Clark", Age: 31, City: "New Orleans" },
  { ID: 29, Name: "Zachary Turner", Age: 30, City: "Orlando" },
  { ID: 30, Name: "Alice Brown", Age: 27, City: "Tampa" },
  { ID: 31, Name: "Bob Clark", Age: 29, City: "Fort Worth" },
  { ID: 32, Name: "Cynthia Turner", Age: 28, City: "San Jose" },
  { ID: 33, Name: "David Adams", Age: 31, City: "Memphis" },
  { ID: 34, Name: "Emma Wilson", Age: 30, City: "Louisville" },
  { ID: 35, Name: "Frank Davis", Age: 32, City: "Milwaukee" },
  { ID: 36, Name: "Grace Turner", Age: 29, City: "Oklahoma City" },
  { ID: 37, Name: "Henry Brown", Age: 34, City: "Albuquerque" },
  { ID: 38, Name: "Ivy Turner", Age: 28, City: "El Paso" },
  { ID: 39, Name: "Jack Taylor", Age: 33, City: "Jacksonville" },
  { ID: 40, Name: "Karen Clark", Age: 30, City: "Tucson" },
  { ID: 41, Name: "Leo Turner", Age: 29, City: "Fresno" },
  { ID: 42, Name: "Megan Adams", Age: 27, City: "Mesa" },
  { ID: 43, Name: "Nathan Davis", Age: 32, City: "Colorado Springs" },
  { ID: 44, Name: "Olivia Turner", Age: 31, City: "Arlington" },
  { ID: 45, Name: "Peter Adams", Age: 30, City: "Bakersfield" },
  { ID: 46, Name: "Quincy Turner", Age: 28, City: "Anaheim" },
  { ID: 47, Name: "Rachel Clark", Age: 33, City: "Honolulu" },
  { ID: 48, Name: "Samuel Adams", Age: 29, City: "Pittsburgh" },
  { ID: 49, Name: "Tina Turner", Age: 30, City: "Lexington" },
  { ID: 50, Name: "Ulysses Adams", Age: 31, City: "Anchorage" },
];
